#!/usr/bin/env bash
set -evxuo pipefail

function _log {
    >&2 printf "[$(date -u)] %s\n" "${@}"
}

function _publish {
    set -evxuo pipefail
    _log "Publishing..."
    pushd "$(git rev-parse --show-toplevel)"
    local branch="$(git rev-parse --abbrev-ref HEAD)"
    git checkout publish
    git pull origin publish
    find . -mindepth 1 -maxdepth 1 ! -name '.git' ! -name '.gitignore' -exec echo {} +
    cp -r dist/* .
    git add .
    git commit -m "update"
    git push origin publish
    git checkout "${branch}"
}

time _publish "${@}"
